/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\mariokarttest.glb --shadows 
*/

import React, { useEffect, useRef } from 'react'
import { Cylinder, OrbitControls, Sphere, useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import FakeGlowMaterial from '../../ShaderMaterials/FakeGlow/FakeGlowMaterial'
import FakeFlame from '../../ShaderMaterials/FakeFlame/FakeFlame'
import { useStore } from '../../store'
import gsap from 'gsap'

export function Mario({ currentSpeed, steeringAngleWheels, isBoosting, shouldLaunch, ...props }) {
  const { nodes, materials } = useGLTF('./models/characters/mariokarttest.glb')

  const frontLeftWheel = useRef()
  const frontRightWheel = useRef()
  const rearWheels = useRef()
  const frontWheels = useRef()
  const [scale, setScale] = React.useState(1)
  const { actions } = useStore()
  const [shouldSlow, setShouldSlow] = React.useState(false)
  const mario = useRef();
  // isBoosting = true;

  useFrame((_,delta) => {
    const rotation = currentSpeed / 100
    frontLeftWheel.current.rotation.x += rotation
    frontRightWheel.current.rotation.x += rotation
    rearWheels.current.rotation.x += rotation
    frontWheels.current.rotation.y = steeringAngleWheels
    if (isBoosting){
      setScale(Math.min(scale + 0.05 * 144 * delta, 1))
    } else {
      setScale(Math.max(scale - 0.03 * 144 * delta, 0))
    }
    setShouldSlow(actions.getShouldSlowDown());
  })

  useEffect(() => {
    if (shouldLaunch) {
      gsap.to(mario.current.rotation, {duration: 1.5, y: Math.PI * 3})
      mario.current.rotation.set(0, 0, 0);
    }
  }, [shouldLaunch])
  return (
    <group
      {...props}
      rotation={[0, Math.PI, 0]}
      dispose={null}
      ref={mario}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mt_kart_Mario_S.geometry}
        material={materials.mt_kart_Mario_S}
      />
      <mesh
        ref={rearWheels}
        castShadow
        receiveShadow
        geometry={nodes.mt_Kart_Mario_Tire_S001.geometry}
        material={materials.mt_Kart_Mario_Tire_S}
        position={[0, 0.22, -0.347]}
      />
      <group ref={frontWheels}>
        <mesh
          ref={frontLeftWheel}
          castShadow
          receiveShadow
          geometry={nodes.mt_Kart_Mario_Tire_S002.geometry}
          material={materials.mt_Kart_Mario_Tire_S}
          position={[0.37, 0.193, 0.441]}
        />
        <mesh
          ref={frontRightWheel}
          castShadow
          receiveShadow
          geometry={nodes.mt_Kart_Mario_Tire_S003.geometry}
          material={materials.mt_Kart_Mario_Tire_S}
          position={[-0.37, 0.193, 0.441]}
          rotation={[-Math.PI, 0, 0]}
          scale={-1}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mt_mario.geometry}
        material={materials.mt_mario}
      />
      <Sphere
        position={[0, 0.6, -1.2]}
        scale={scale * 1.2}
      >
        <FakeGlowMaterial />
      </Sphere>

      <Cylinder
        args={[0.1, 0, 1, 128, 64, true]}
        position={[0.3, 0.65, -1.35]}
        rotation={[Math.PI / 1.5, 0, 0]}
        scale={scale}
        
      >
        <FakeFlame isBoosting={isBoosting}/>
      </Cylinder>

      <Cylinder
        args={[0.1, 0, 1, 128, 64, true]}
        position={[-0.3, 0.65, -1.35]}
        rotation={[Math.PI / 1.5, 0, 0]}
        scale={scale}
      >
        <FakeFlame isBoosting={isBoosting} />
      </Cylinder>
      <Cylinder
        args={[0.09, 0, 1, 128, 64, true]}
        position={[0.18, 0.75, -1.1]}
        rotation={[Math.PI / 1.5, 0, 0]}
        scale={scale * 0.8}
      >
        <FakeFlame isBoosting={isBoosting} />
      </Cylinder>
      <Cylinder
        args={[0.09, 0, 1, 128, 64, true]}
        position={[-0.18, 0.75, -1.1]}
        rotation={[Math.PI / 1.5, 0, 0]}
        scale={scale * 0.8}
      >
        <FakeFlame isBoosting={isBoosting}/>
      </Cylinder>

    </group>
  )
}

useGLTF.preload('./models/characters/mariokarttest.glb')
