/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\mario_kart_item_box.glb 
Author: Bscott5 (https://sketchfab.com/Bscott5)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mario-kart-item-box-8f6a2b6b17b844c5b5dfa38375289975
Title: Mario Kart Item Box
*/

import React, { useRef } from "react";
import { useGLTF, Float, MeshTransmissionMaterial, RoundedBox } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";
import { useStore } from "../../store";

export function ItemBox(props) {

  const { actions } = useStore();
  return (
    <>
        <RigidBody type="fixed" name="itemBox"
      sensor
      onIntersectionEnter={() => {
        actions.setItem();
        
      }}
      position={props.position}
      >
        <mesh>
          <boxGeometry args={[1, 1, 1]} />
          <meshStandardMaterial color="green" />
        </mesh>
      </RigidBody>
    <group {...props} dispose={null}>
    

      <Float
        speed={2} // Animation speed, defaults to 1
        rotationIntensity={20} // XYZ rotation intensity, defaults to 1
        floatIntensity={1} // Up/down float intensity, works like a multiplier with floatingRange,defaults to 1
        floatingRange={[1, 2]} // Range of y-axis values the object will float within, defaults to [-0.1,0.1]
      >
          <mesh>
        <boxGeometry args={[1, 1, 1]} />
        <meshBasicMaterial color="green" />
        </mesh>
      </Float>
    </group>
    </>
  );
}
