/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\super_mario_bros_coin.glb --shadows --transform 
Files: .\super_mario_bros_coin.glb [48.84KB] > C:\Users\mouli\dev\r3f-vite-starter\public\models\misc\super_mario_bros_coin-transformed.glb [6.12KB] (87%)
Author: BranHelsing (https://sketchfab.com/BranHelsing)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/super-mario-bros-coin-aa97e093847a439f9feb064134813806
Title: Super Mario Bros Coin
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { RigidBody } from "@react-three/rapier";
import { useStore } from "../../store";

export function Coin(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "./models/misc/super_mario_bros_coin-transformed.glb"
  );
  const { actions } = useStore();
  const [scale, setScale] = React.useState(0.424);
  const frames = useRef(0);
  useFrame((state, delta) => {

    group.current.rotation.y += 4 * delta;
    if(scale < 0.424 && frames.current > 0){
      frames.current -= 1 * delta * 144;

    }
    if(frames.current <= 0){
      setScale(Math.min(scale + 0.5 * delta, 0.424));
      if(body.current){
        body.current.setEnable(true);
      }
    }
  });

  const body = useRef();

  return (
    <>
      <RigidBody
        type="fixed"
        name="coin"
        sensor
        onIntersectionEnter={({ manifold, target, other}) => {
          if(other.rigidBodyObject.name === "player"){
            actions.addCoins();
            setScale(0);
            frames.current = 600;
            body.current.setEnable(false);
          }
        }}
        position={props.position}
      >
        <mesh
        ref={group}
          castShadow
          receiveShadow
          geometry={nodes.Coin_CoinBlinn_0.geometry}
          material={materials.CoinBlinn}
          scale={scale}
        />
      </RigidBody>
    </>
  );
}

useGLTF.preload("./models/misc/super_mario_bros_coin-transformed.glb");
