/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\super_mario_bros_coin.glb --shadows --transform 
Files: .\super_mario_bros_coin.glb [48.84KB] > C:\Users\mouli\dev\r3f-vite-starter\public\models\misc\super_mario_bros_coin-transformed.glb [6.12KB] (87%)
Author: BranHelsing (https://sketchfab.com/BranHelsing)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/super-mario-bros-coin-aa97e093847a439f9feb064134813806
Title: Super Mario Bros Coin
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Coin(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/misc/super_mario_bros_coin-transformed.glb')
  const { actions } = useAnimations(animations, group)

  useFrame((state, delta) => {
    group.current.rotation.y += 4 * delta
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.588}>
          <group name="Coin" scale={0.424}>
            <mesh name="Coin_CoinBlinn_0" castShadow receiveShadow geometry={nodes.Coin_CoinBlinn_0.geometry} material={materials.CoinBlinn} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/misc/super_mario_bros_coin-transformed.glb')
