/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --shadows --instance mario-circuit-test.glb 
Files: mario-circuit-test.glb [4.2MB] > C:\Users\mouli\Mario-Kart-3.js\public\mario-circuit-test-transformed.glb [1.81MB] (57%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Track(props) {
  const { nodes, materials } = useGLTF('./models/mario-circuit-test-transformed.glb')
  return (
    <group {...props} dispose={null} position={[155, -28., 15]} scale={0.08}>
      <mesh name="ground" castShadow receiveShadow geometry={nodes.Object_10.geometry} material={materials.material_5} />
      <mesh name="ground" castShadow receiveShadow geometry={nodes.Object_11.geometry} material={materials.material_6} />
      <mesh name="ground" castShadow receiveShadow geometry={nodes.Object_12.geometry} material={materials.material_7} />
      <mesh name="ground" castShadow receiveShadow geometry={nodes.Object_13.geometry} material={materials.material_8} />
      <mesh name="ground" castShadow receiveShadow geometry={nodes.Object_18.geometry} material={materials.material_12} />
      <mesh name="ground" castShadow receiveShadow geometry={nodes.Object_22.geometry} material={materials.material_16} />
      <mesh name="ground" castShadow receiveShadow geometry={nodes.Object_24.geometry} material={materials.material_18} />
      <mesh name="ground" castShadow receiveShadow geometry={nodes.Object_25.geometry} material={materials.material_19} />
      <mesh name="ground" castShadow receiveShadow geometry={nodes.Object_27.geometry} material={materials.material_21} />
      <mesh name="ground" castShadow receiveShadow geometry={nodes.Object_47.geometry} material={materials.material_3} />
    </group>
  )
}

useGLTF.preload('./models/mario-circuit-test-transformed.glb')
