/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\front_wheel.glb 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import gsap from "gsap";

export function FrontWheel({
  isLeftWheel,
  currentSpeed,
  left,
  right,
  ...props
}) {
  const { nodes, materials } = useGLTF("./models/front_wheel.glb");
  const wheel = useRef();
  const rotation = isLeftWheel ? [0, Math.PI, 0] : [0, 0, 0];

  useEffect(() => {
    
  }, [currentSpeed, left, right]);
  return (
    <group {...props} dispose={null}>
      <group ref={wheel} rotation={rotation}>
        <mesh
          geometry={nodes.FL_Wheel_Body_0001.geometry}
          material={materials.Body}
        />
        <mesh
          geometry={nodes.FL_Wheel_Rims_0001.geometry}
          material={materials.Rims}
        />
        <mesh
          geometry={nodes.FL_Wheel_Tires_0001.geometry}
          material={materials.Tires}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/front_wheel.glb");
