/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\mariokarttest.glb --shadows 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Mario({currentSpeed, steeringAngleWheels, ...props}) {
  const { nodes, materials } = useGLTF('./models/mariokarttest.glb')

  const frontLeftWheel = useRef()
  const frontRightWheel = useRef()
  const rearWheels = useRef()
  const frontWheels = useRef()

  useFrame(() => {
    const rotation = currentSpeed / 100
    frontLeftWheel.current.rotation.x += rotation
    frontRightWheel.current.rotation.x += rotation
    rearWheels.current.rotation.x += rotation
    frontWheels.current.rotation.y = steeringAngleWheels

  })
  return (
    <group {...props} rotation={[0, Math.PI, 0]} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.mt_kart_Mario_S.geometry} material={materials.mt_kart_Mario_S} />
      <mesh ref={rearWheels} castShadow receiveShadow geometry={nodes.mt_Kart_Mario_Tire_S001.geometry} material={materials.mt_Kart_Mario_Tire_S} position={[0, 0.22, -0.347]} />
      <group ref={frontWheels} >
      <mesh ref={frontLeftWheel} castShadow receiveShadow geometry={nodes.mt_Kart_Mario_Tire_S002.geometry} material={materials.mt_Kart_Mario_Tire_S} position={[0.370, 0.193, 0.441]} />
      <mesh ref={frontRightWheel} castShadow receiveShadow geometry={nodes.mt_Kart_Mario_Tire_S003.geometry} material={materials.mt_Kart_Mario_Tire_S} position={[-0.370, 0.193, 0.441]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.mt_mario.geometry} material={materials.mt_mario} />
    </group>
  )
}

useGLTF.preload('./models/mariokarttest.glb')
