/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\racing_kart.glb --transform 
Files: .\racing_kart.glb [1.83MB] > C:\Users\mouli\dev\r3f-vite-starter\public\models\racing_kart-transformed.glb [150.05KB] (92%)
Author: scailman (https://sketchfab.com/scailman)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/racing-kart-f48f8e66bba6492eadc000d2585b6a32
Title: Racing Kart
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import gsap from "gsap";

export function Model({ steeringAngle, speed, left, right, ...props }) {
  const { nodes, materials } = useGLTF("./models/racing_kart-transformed.glb");


  return (
    <group {...props} dispose={null}>
      <group rotation={[0, Math.PI, 0]}>
        <mesh
          geometry={nodes.drivers_Visera_0.geometry}
          material={materials.Visera}
          position={[0, 1.055, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.drivers_Mono1_0.geometry}
          material={materials.Mono1}
          position={[0, 1.055, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.drivers_Casco2_0.geometry}
          material={materials.Casco2}
          position={[0, 1.055, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.drivers_Casco_0.geometry}
          material={materials.Casco}
          position={[0, 1.055, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.drivers_Piel_0.geometry}
          material={materials.Piel}
          position={[0, 1.055, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.drivers_Mono2_0.geometry}
          material={materials.Mono2}
          position={[0, 1.055, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.drivers_Mono2_0_1.geometry}
          material={materials.Mono2_0}
          position={[0, 1.055, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.Chassis_Rims_0.geometry}
          material={materials.Rims}
          position={[-0.221, 0.132, 0.413]}
        />
        <mesh
          geometry={nodes.Chassis_Chassis_0.geometry}
          material={materials.Chassis}
          position={[-0.221, 0.132, 0.413]}
        />
        {/* <mesh
          geometry={nodes.FR_Wheel_Tires_0.geometry}
          material={materials.Tires}
          position={[-0.033, 0.157, 0.412]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.FR_Wheel_Body_0.geometry}
          material={materials.Body}
          position={[-0.033, 0.157, 0.412]}
          rotation={[-Math.PI / 2, 0, 0]}
        /> */}
        <mesh
          geometry={nodes.Body_Lines2_0.geometry}
          material={materials.Lines2}
          position={[-0.351, 0.15, -0.124]}
          rotation={[0, -1.57, 0]}
        />
        <mesh
          geometry={nodes.Engine_Engine_0.geometry}
          material={materials.Engine}
          position={[-0.229, 0.22, -0.465]}
          rotation={[0, -1.57, 0]}
          scale={[1.31, 1.31, 1.041]}
        />
        <mesh
          geometry={nodes.Engine_Deposit_0.geometry}
          material={materials.Deposit}
          position={[-0.229, 0.22, -0.465]}
          rotation={[0, -1.57, 0]}
          scale={[1.31, 1.31, 1.041]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/racing_kart-transformed.glb");
