/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\rear_wheels.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function RearWheels(props) {
  const { nodes, materials } = useGLTF('./models/rear_wheels.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.463, 0.157, -0.622]}>
        <group position={[-0.431, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.RL_Wheel_Body_0.geometry} material={materials.Body} />
          <mesh geometry={nodes.RL_Wheel_Rims_0.geometry} material={materials.Rims} />
          <mesh geometry={nodes.RL_Wheel_Tires_0.geometry} material={materials.Tires} />
          <mesh geometry={nodes.RL_Wheel_Tires_0001.geometry} material={materials.Tires} />
        </group>
      </group>
      <group position={[-0.463, 0.157, -0.622]}>
        <group position={[0.431, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.RR_Wheel_Body_0.geometry} material={materials.Body} />
          <mesh geometry={nodes.RR_Wheel_Rims_0.geometry} material={materials.Rims} />
          <mesh geometry={nodes.RR_Wheel_Tires_0.geometry} material={materials.Tires} />
          <mesh geometry={nodes.RR_Wheel_Tires_0001.geometry} material={materials.Tires} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/rear_wheels.glb')
