/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\spafrancorchamps-REALISTIC.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function Track(props) {
  const { nodes, materials } = useGLTF('./models/spafrancorchamps-REALISTIC.glb')
  return (
    <group {...props} dispose={null}>
      <RigidBody type="fixed" name={'terrain'} colliders="trimesh" userData={'terrain'} position={[0, 1, 0]}>
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} />
      </RigidBody>
    </group>
  )
}

useGLTF.preload('./models/spafrancorchamps-REALISTIC.glb')
